name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: phpstan, php-cs-fixer
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Static Analysis
        run: vendor/bin/phpstan analyse --configuration=phpstan.neon.dist
      - name: PHPUnit
        run: vendor/bin/phpunit --colors=always

